apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    name: eureka-server
    visualize: "true"
spec:
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  selector:
    name: eureka-server
  sessionAffinity: None  
  type: ClusterIP
status:
  loadBalancer: {}  
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
    visualize: "true"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
        version: "v1"
        visualize: "true"
    spec:
      containers:
      - name: eureka-server
        image: gcr.io/appsutility-141503/eureka-server:v1
        imagePullPolicy: Always     
        resources:
            requests:
              memory: "128Mi"
              cpu: "300m"
            limits:
              memory: "256Mi"
              cpu: "500m"          
        ports:
          - name: http
            containerPort: 8761           