apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
    visualize: "true"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
        version: "v1"
        visualize: "true"
    spec:
      containers:
      - name: eureka-server
        image: gcr.io/appsutility-141503/eureka-server:v1
        imagePullPolicy: Always    
        resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"          
        ports:
          - name: http
            containerPort: 8761
      imagePullSecrets:
      - name: gcr.io             
---            

apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    name: eureka-server
    visualize: "true"
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  sessionAffinity: None    
            
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: eureka-server
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eureka-server
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50